"""
Daily regression check: re-test every optimal brain on FRESH physics arenas.

The held-out test arenas are fixed, so a brain could in principle look good on
them by luck. Each day this draws a new set of random arenas (seeded by the
date, so a day's check is reproducible), runs the deployed brain on them in
MuJoCo, appends the result to training/<skill>/checks.jsonl and rewrites
training/CHECKS.md. The supervisor runs it once a day; nothing here changes a
brain, it only measures.

    ..\\..\\.venv-sim\\Scripts\\python recheck.py            # 16 fresh arenas per optimal brain
    ..\\..\\.venv-sim\\Scripts\\python recheck.py --n 32 --all
"""
from __future__ import annotations

import argparse
import json
from datetime import date, datetime
from pathlib import Path

import numpy as np

import brain as B
import tasks as T
from train_brains import TRAIN_DIR, STATE, TEST_OPTIMAL, is_optimal, physics_eval, wilson

WATCH = 0.80          # below this on fresh arenas the brain is flagged for attention


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--n", type=int, default=16, help="fresh physics arenas per brain")
    ap.add_argument("--all", action="store_true", help="check every brain, not only optimal ones")
    args = ap.parse_args()
    brains = B.Brain(STATE)
    day = date.today()
    for k, task in enumerate(T.TASKS):
        p = TRAIN_DIR / task / "status.json"
        st = json.loads(p.read_text()) if p.exists() else None
        if not st or not st.get("best") or not (args.all or is_optimal(st)):
            continue
        seed = 40_000_000 + day.toordinal() * 10 + k          # new arenas every day
        rate, reward, errors = physics_eval(brains.theta(task), task, args.n, seed)
        lo, hi = wilson(rate, args.n)
        row = {"date": day.isoformat(), "time": datetime.now().isoformat(timespec="seconds"),
               "brain_round": st["best"]["round"], "n": args.n, "success": rate,
               "ci": [round(lo, 3), round(hi, 3)], "reward": reward, "errors": errors, "seed": seed}
        with open(TRAIN_DIR / task / "checks.jsonl", "a", encoding="utf-8") as fh:
            fh.write(json.dumps(row) + "\n")
        print(f"{task:<13} round {row['brain_round']:>4}: {rate:.0%} of {args.n} fresh arenas "
              f"(95% CI {lo:.0%}-{hi:.0%}){'  <-- below watch line' if rate < WATCH else ''}", flush=True)
    write_report()


def write_report():
    lines = ["# Daily fresh-arena checks", "",
             f"*Auto-generated by `recheck.py`, last updated {datetime.now().isoformat(timespec='seconds')}.*", "",
             "Every day each optimal brain is re-run in MuJoCo on a new set of random arenas it has never "
             f"seen. The fixed held-out test decides 'optimal' (>= {TEST_OPTIMAL:.0%}); these checks watch for "
             f"brains that only look good on that fixed set. Anything under {WATCH:.0%} is flagged.", "",
             "| skill | last check | brain round | fresh arenas | success (95% CI) | last 7 checks |",
             "|---|---|---:|---:|---|---|"]
    for task in T.TASKS:
        p = TRAIN_DIR / task / "checks.jsonl"
        if not p.exists():
            continue
        rows = [json.loads(l) for l in p.read_text(encoding="utf-8").splitlines() if l.strip()]
        if not rows:
            continue
        r = rows[-1]
        flag = " ⚠️" if r["success"] < WATCH else ""
        hist = " ".join(f"{x['success']:.0%}" for x in rows[-7:])
        lines.append(f"| {T.PRETTY[task]} | {r['date']} | {r['brain_round']} | {r['n']} | "
                     f"{r['success']:.0%} ({r['ci'][0]:.0%}-{r['ci'][1]:.0%}){flag} | {hist} |")
    (TRAIN_DIR / "CHECKS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
